# Generated by Django 4.0.4 on 2022-06-07 17:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Africa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('lugar', models.CharField(max_length=300)),
                ('experiencia', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=300)),
                ('fecha', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='America',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('lugar', models.CharField(max_length=300)),
                ('experiencia', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=300)),
                ('fecha', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Asia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('lugar', models.CharField(max_length=300)),
                ('experiencia', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=300)),
                ('fecha', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Europa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('lugar', models.CharField(max_length=300)),
                ('experiencia', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=300)),
                ('fecha', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Oceania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('lugar', models.CharField(max_length=300)),
                ('experiencia', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=300)),
                ('fecha', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
