# Generated by Django 4.0.4 on 2022-05-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajeros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='america',
            old_name='subitulo',
            new_name='subtitulo',
        ),
    ]
